before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: PjdshCqWOHv81XBpHweqH5IC8rC9ooABkECN6I6ydUJ6uUE+1W2+jOY4YKEIgqJH/VLvNEclwmFxfk6gM8H4chQ4K1o6nGSQQEwpZa2KQ2ss+OJEUITNlQxB453xtJeZaAYTcMxIb/9+F/GTV6fYDVstXEDBwrbnlpaB0tJS0K4XuLwP8stVxyFzfJ//s2GeE+mW3gK6bbpSbrSjfTRwdnQVqBCVXwW9hdNdDAkBgt6VgbURzGhdV18T2CwbfBuVPdYApM5GhDxU3aC6qPFsBiS9c1elMpsedlrS4vOYREIuZ3y1ddBC4+DuWn42yLFZ/972xIKuplg6KfTpKXddkcyBK79Z8I0f8+iAEr1p0wYererrcGY6cK6L+4g0jeEcsmbFHHKyecTu1ZuU1bdbxawq5m+dyZkXs1761jdKMjx8Zg1UgZNP5Wn2/86kvTeDghalZ67vId3wyhKPmKIRyqe/MlferqNDFnsANhPpbrruPmW80/X/zZw5Z2kQ25J+CyqwZB6EA0m6ibkzu0qJWUN465JcgL1EHRb1hX19aV3OipJLnlkSFAvqGJ+0mBFDb07EMi96Ghxmgvwx6mEIGqAB356FaZydy+jfQ124D/7d8/6ozbfc+41ZpcrL930K6AVVND4GlJVIsqNeTz/XF1RTHH1/nfyqkQQC8Wr9IoU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
